table 'Purchase Orders'
	lineageTag: b8bcf907-4802-483c-ae85-16af951292de

	column 'PO ID'
		dataType: string
		lineageTag: 2408bd2d-ccee-49ed-a347-3ab90452b735
		summarizeBy: none
		sourceColumn: PO ID

		annotation SummarizationSetBy = Automatic

	column 'PO Number'
		dataType: string
		lineageTag: 800500d6-65c9-4546-8de8-7c5eeb2f9821
		summarizeBy: none
		sourceColumn: PO Number

		annotation SummarizationSetBy = Automatic

	column 'Vendor Name'
		dataType: string
		lineageTag: a987a772-4d03-4e27-b489-1254007a94c1
		summarizeBy: none
		sourceColumn: Vendor Name

		annotation SummarizationSetBy = Automatic

	column 'Vendor ID'
		dataType: string
		lineageTag: ea6863f8-4001-4f49-b31f-5de7be4a2075
		summarizeBy: none
		sourceColumn: Vendor ID

		annotation SummarizationSetBy = Automatic

	column 'Program ID'
		dataType: string
		lineageTag: 58a10fe5-b655-459d-b56f-1052598a453b
		summarizeBy: none
		sourceColumn: Program ID

		annotation SummarizationSetBy = Automatic

	column 'Program Name'
		dataType: string
		lineageTag: 7e18a341-1a95-4085-af4f-5cd08557a8f7
		summarizeBy: none
		sourceColumn: Program Name

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 95e2e833-3a51-4c1b-93d1-583e667f719b
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 64d36d4b-92f6-4363-b55a-2c9764dbb4d8
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: 7e1f22fe-ec4e-4a35-a415-3d359ec9a2ac
			defaultHierarchy: LocalDateTable_ad29e3ff-a357-446b-9bc3-7b33eb19b6e9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Delivery Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e24a77cc-d871-4f6d-90c2-af2b90822faf
		summarizeBy: none
		sourceColumn: Delivery Date

		variation Variation
			isDefault
			relationship: 54497b58-e974-4b75-bc45-4dbba6cf6406
			defaultHierarchy: LocalDateTable_1ad8adfb-1358-46c8-a812-d6a534a80542.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'PO Amount'
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f84fc5df-1876-4e09-b38d-b382546d0765
		summarizeBy: sum
		sourceColumn: PO Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Amount Paid'
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: cd5745ce-6cb2-458c-aba6-a576e5250d5e
		summarizeBy: sum
		sourceColumn: Amount Paid

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Amount Remaining'
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 1717b9cc-a5b1-4b1f-92e0-4957d8f534f6
		summarizeBy: sum
		sourceColumn: Amount Remaining

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'PO Status'
		dataType: string
		lineageTag: accbaa61-7028-4ee6-9692-c6a8be24851b
		summarizeBy: none
		sourceColumn: PO Status

		annotation SummarizationSetBy = Automatic

	column 'Approver Name'
		dataType: string
		lineageTag: 537f0675-9665-4dbb-85bc-7bca87d65f01
		summarizeBy: none
		sourceColumn: Approver Name

		annotation SummarizationSetBy = Automatic

	column 'Cost Center'
		dataType: string
		lineageTag: 36bbf433-aca4-4d26-a408-ea0837950dd0
		summarizeBy: none
		sourceColumn: Cost Center

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: dd966f4d-ae22-4d2e-b3e3-5f2c88dedd53
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column 'CLIN Number'
		dataType: string
		lineageTag: 510c20ec-604e-43a9-a7e6-afeb5bb3c825
		summarizeBy: none
		sourceColumn: CLIN Number

		annotation SummarizationSetBy = Automatic

	partition 'Purchase Orders' = m
		mode: import
		source =
				let
				    // Step 1: Load the CSV file
				    Source = Csv.Document(
				    File.Contents("C:\Projects\PowerBI\workshop\PBI_Factory\TrainingData\Financial Data - Purchase Orders.csv"),
				        [Delimiter=",", Columns=17, Encoding=65001, QuoteStyle=QuoteStyle.None]
				    ),
				
				    // Step 2: Promote the first row to column headers
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				
				    // Step 3: Remove duplicate rows based on PO ID
				    #"Removed Duplicates" = Table.Distinct(#"Promoted Headers", {"PO ID"}),
				
				    // Step 4: Trim spaces from all text columns
				    #"Trimmed Text" = Table.TransformColumns(#"Removed Duplicates", {
				        {"PO ID", Text.Trim, type text},
				        {"PO Number", Text.Trim, type text},
				        {"Vendor Name", Text.Trim, type text},
				        {"Vendor ID", Text.Trim, type text},
				        {"Program ID", Text.Trim, type text},
				        {"Program Name", Text.Trim, type text},
				        {"Description", Text.Trim, type text},
				        {"PO Status", Text.Trim, type text},
				        {"Approver Name", Text.Trim, type text},
				        {"Cost Center", Text.Trim, type text},
				        {"Priority", Text.Trim, type text},
				        {"CLIN Number", Text.Trim, type text}
				    }),
				
				    // Step 5: Remove $ from PO Amount
				    #"Removed $ from PO Amount" = Table.ReplaceValue(#"Trimmed Text", "$", "", Replacer.ReplaceText, {"PO Amount"}),
				
				    // Step 6: Remove commas from PO Amount
				    #"Removed , from PO Amount" = Table.ReplaceValue(#"Removed $ from PO Amount", ",", "", Replacer.ReplaceText, {"PO Amount"}),
				
				    // Step 7: Remove $ from Amount Paid
				    #"Removed $ from Amount Paid" = Table.ReplaceValue(#"Removed , from PO Amount", "$", "", Replacer.ReplaceText, {"Amount Paid"}),
				
				    // Step 8: Remove commas from Amount Paid
				    #"Removed , from Amount Paid" = Table.ReplaceValue(#"Removed $ from Amount Paid", ",", "", Replacer.ReplaceText, {"Amount Paid"}),
				
				    // Step 9: Remove $ from Amount Remaining
				    #"Removed $ from Amount Remaining" = Table.ReplaceValue(#"Removed , from Amount Paid", "$", "", Replacer.ReplaceText, {"Amount Remaining"}),
				
				    // Step 10: Remove commas from Amount Remaining
				    #"Removed , from Amount Remaining" = Table.ReplaceValue(#"Removed $ from Amount Remaining", ",", "", Replacer.ReplaceText, {"Amount Remaining"}),
				
				    // Step 11: Replace NULL with 0 in Amount Paid
				    #"Replaced NULL" = Table.ReplaceValue(#"Removed , from Amount Remaining", "NULL", "0", Replacer.ReplaceText, {"Amount Paid"}),
				
				    // Step 12: Replace dash (-) with 0 in Amount Paid
				    #"Replaced Dash" = Table.ReplaceValue(#"Replaced NULL", "-", "0", Replacer.ReplaceValue, {"Amount Paid"}),
				
				    // Step 13: Change amount columns to Decimal Number type
				    #"Changed Amount Types" = Table.TransformColumnTypes(#"Replaced Dash", {
				        {"PO Amount", type number},
				        {"Amount Paid", type number},
				        {"Amount Remaining", type number}
				    }),
				
				    // Step 14: Change Order Date to Date type
				    #"Changed Order Date Type" = Table.TransformColumnTypes(#"Changed Amount Types", {
				        {"Order Date", type date}
				    }),
				
				    // Step 15: Replace errors in Order Date (from non-standard date formats)
				    #"Replaced Order Date Errors" = Table.ReplaceErrorValues(#"Changed Order Date Type", {{"Order Date", null}}),
				
				    // Step 16: Change Delivery Date to Date type
				    #"Changed Delivery Date Type" = Table.TransformColumnTypes(#"Replaced Order Date Errors", {
				        {"Delivery Date", type date}
				    }),
				
				    // Step 17: Replace errors in Delivery Date
				    #"Replaced Delivery Date Errors" = Table.ReplaceErrorValues(#"Changed Delivery Date Type", {{"Delivery Date", null}}),
				
				    // Step 18: Capitalize Each Word in PO Status
				    #"Capitalized PO Status" = Table.TransformColumns(#"Replaced Delivery Date Errors", {
				        {"PO Status", Text.Proper, type text}
				    }),
				
				    // Step 19: Capitalize Each Word in Priority
				    #"Capitalized Priority" = Table.TransformColumns(#"Capitalized PO Status", {
				        {"Priority", Text.Proper, type text}
				    }),
				
				    // Step 20: Fix vendor name inconsistencies
				    #"Fixed Apex" = Table.ReplaceValue(#"Capitalized Priority", "Apex Dynamics Corp.", "Apex Dynamics Corp", Replacer.ReplaceText, {"Vendor Name"}),
				    #"Fixed Centurion" = Table.ReplaceValue(#"Fixed Apex", "Centurion Inc.", "Centurion Inc", Replacer.ReplaceText, {"Vendor Name"}),
				
				    // Step 21: Fix shortened program names
				    #"Fixed Program Name" = Table.ReplaceValue(#"Fixed Centurion", "Satellite Comm Upgrade", "Satellite Communications Upgrade", Replacer.ReplaceText, {"Program Name"})
				in
				    #"Fixed Program Name"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

